name: odoo-selenium
services:
  odoo:
    image: vauxoo/odoo-selenium:${ODOO_VERSION-16}
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      args:
        ODOO_VERSION: ${ODOO_VERSION-16}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 1s
      timeout: 30s
      retries: 30
